# Define required macros here
SHELL = /bin/sh

OBJS =  main.o
CFLAGS = -lws2_32 # -Wall -g 
CC = g++

main: main.cpp src/server.cpp src/parser.cpp src/request_handler.cpp
   $(CC) $(CFLAGS) -o server